repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        types: [text]
      - id: check-yaml
  - repo: https://github.com/Enter-tainer/typstyle
    rev: v0.11.27
    hooks:
      - id: typstyle
